"""add_direct_messaging_tables

Revision ID: 73d266e9d519
Revises: 8991bb29a12a
Create Date: 2026-07-12 11:13:59.365030

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73d266e9d519'
down_revision: str | None = '8991bb29a12a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_conversations',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_conversations_created_by'), 'dm_conversations', ['created_by'], unique=False)
    op.create_index(op.f('ix_dm_conversations_deleted_at'), 'dm_conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dm_conversations_last_message_at'), 'dm_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_dm_conversations_type'), 'dm_conversations', ['type'], unique=False)
    op.create_table('dm_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_member_id', sa.Uuid(), nullable=False),
    sa.Column('sender_team_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('reply_to_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['dm_conversations.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['dm_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dm_messages_conv_created', 'dm_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dm_messages_conversation_id'), 'dm_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_dm_messages_created_at'), 'dm_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_dm_messages_deleted_at'), 'dm_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dm_messages_sender_member_id'), 'dm_messages', ['sender_member_id'], unique=False)
    op.create_index(op.f('ix_dm_messages_sender_team_id'), 'dm_messages', ['sender_team_id'], unique=False)
    op.create_table('dm_conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_id', sa.Uuid(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['dm_conversations.id'], ),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['dm_messages.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_conversation_participants_conversation_id'), 'dm_conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_dm_conversation_participants_member_id'), 'dm_conversation_participants', ['member_id'], unique=False)
    op.create_index(op.f('ix_dm_conversation_participants_team_id'), 'dm_conversation_participants', ['team_id'], unique=False)
    op.create_index('ix_dm_participants_conv_member', 'dm_conversation_participants', ['conversation_id', 'member_id'], unique=True, postgresql_where=sa.text('member_id IS NOT NULL AND left_at IS NULL'))
    op.create_index('ix_dm_participants_conv_team', 'dm_conversation_participants', ['conversation_id', 'team_id'], unique=True, postgresql_where=sa.text('team_id IS NOT NULL AND left_at IS NULL'))
    op.create_table('dm_message_attachments',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_message_attachments_message_id'), 'dm_message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dm_message_attachments_message_id'), table_name='dm_message_attachments')
    op.drop_table('dm_message_attachments')
    op.drop_index('ix_dm_participants_conv_team', table_name='dm_conversation_participants', postgresql_where=sa.text('team_id IS NOT NULL AND left_at IS NULL'))
    op.drop_index('ix_dm_participants_conv_member', table_name='dm_conversation_participants', postgresql_where=sa.text('member_id IS NOT NULL AND left_at IS NULL'))
    op.drop_index(op.f('ix_dm_conversation_participants_team_id'), table_name='dm_conversation_participants')
    op.drop_index(op.f('ix_dm_conversation_participants_member_id'), table_name='dm_conversation_participants')
    op.drop_index(op.f('ix_dm_conversation_participants_conversation_id'), table_name='dm_conversation_participants')
    op.drop_table('dm_conversation_participants')
    op.drop_index(op.f('ix_dm_messages_sender_team_id'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_sender_member_id'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_deleted_at'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_created_at'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_conversation_id'), table_name='dm_messages')
    op.drop_index('ix_dm_messages_conv_created', table_name='dm_messages')
    op.drop_table('dm_messages')
    op.drop_index(op.f('ix_dm_conversations_type'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_last_message_at'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_deleted_at'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_created_by'), table_name='dm_conversations')
    op.drop_table('dm_conversations')
    # ### end Alembic commands ###
